### ISSUE TITLE
[UI] sidebar styles in Firefox

### ISSUE THREAD

**Issue by leiyre** [argilla-io/argilla#132]

**Comment by leiyre** [comment]
@dcfidalgo  can you provide a screenshot or explain a little bit about the strange behaviour in your firefox version. thanks!

**Comment by dcfidalgo** [comment]
Sure, here are two screenshots with my Firefox:

![Screenshot from 2021-06-22 15-03-18](https://user-images.githubusercontent.com/15979778/122929952-ce3d0900-d36b-11eb-937e-26134ad240a3.png)
![Screenshot from 2021-06-22 15-03-31](https://user-images.githubusercontent.com/15979778/122929964-d137f980-d36b-11eb-9723-2cd7415e04c9.png)

And here is a screenshot with my Chrome:

![Screenshot from 2021-06-22 15-04-00](https://user-images.githubusercontent.com/15979778/122930060-eb71d780-d36b-11eb-84b9-353833108e72.png)
