### ISSUE TITLE
Allow copying UI created labels

### ISSUE THREAD

**Issue by dcfidalgo** [argilla-io/argilla#136]
When i create new labels in the UI, and do not annotate anything with these new labels, these new labels will not be copied when doing a `rubrix.load`&`rubrix.log`.

It would be nice to be able to completely copy a data set and its "state".

**Comment by frascuchon** [comment]
This use cases could be better solved by a `rubrix.copy` method. Load/log is a workaround emulation this behaviour but nothing about what original dataset metadata contains (including labels/entities)

**Comment by dcfidalgo** [comment]
Yes, a `rb.copy` method would definitely be nice, but in my case i think i slightly modified the metadata after the `rb.load` step, and uploaded it again. So a `rb.copy` that really just copies the dataset and logs it with a new name, would not have solved my specific use case.

**Comment by frascuchon** [comment]
> Yes, a `rb.copy` method would definitely be nice, but in my case i think i slightly modified the metadata after the `rb.load` step, and uploaded it again. So a `rb.copy` that really just copies the dataset and logs it with a new name, would not have solved my specific use case.

```python
rb.copy("orig_ds", "dest_ds", tags={"override": "orig tags"})
```

Would this `copy` method modification achieve a more general copy flow?

**Comment by dcfidalgo** [comment]
With `tags` you are referring to the tags of a dataset? 

With metadata, I was referring to the metadata of the records, but I cannot recall if the change included some logic or if it was simply a replacement of values. Anyhow, I think this new copy method would definitely be useful.
