### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by firqaaa** [argilla-io/argilla#1500]
Any idea what causes this error? 
`ValueError: Number of classes, 21, does not match size of target_names, 19. Try specifying the labels parameter`

**Comment by frascuchon** [comment]
Hi @firqaaa and thanks for using Rubrix,

Could you please send a little bit more info? Where the error occurs? The complete error trace could help

**Comment by frascuchon** [comment]
Hi, @firqaaa 

Did you manage to solve the problem?

**Comment by frascuchon** [comment]
I will close the issue for now. Please feel free to reopen if you need to include some additional info.
