### ISSUE TITLE
Annotation Guide using Misogyny Use Case

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#172]
This guide will serve as a guide for:

- Training an AMI system with IberEval 2018's dataset
- Annotating and exporting annotations
- Retraining 
- Inter-Annotator Agreement

To simplify the system for the guide, we will exclude Subtask 3 (target) and make Multiclass, but not Multilabel, of Subtask 2 (category). We also need to make the datasers public, the initial and the annotated ones, to make the guide replicable.

Even though it is not a tutorial, it is intended to use runnable code as much as possible.

**Comment by frascuchon** [comment]
Done!
