### ISSUE TITLE
Elasticsearch question

### ISSUE THREAD

**Issue by cceyda** [argilla-io/argilla#182]
(Looking at docker-compose)
Can I use an Elasticsearch instance I already have? for example by creating a `rubrix` user in Elasticsearch. If so;
  - Which roles & permissions would rubrix need?
  - Does rubrix create indexes with a certain name pattern like rubrix_* ? (If so I could just give all permissions for those indexes)
  - How would I pass username/password (environment variable ELASTICSEARCH_USER/ELASTICSEARCH_PASSWORD ? along with ELASTICSEARCH: address)

Or rubrix need full access to the elasticsearch instance, in which case must have its own elasticsearch.

**Comment by frascuchon** [comment]
Hi @cceyda 

Thanks for your question.

Normally you should use your own elasticsearch instance by taking into account some consideration:

* Rubrix will create its es index with `.rubrix_*` pattern, so yes, you should provide all permissions to these kind of indices
* Rubrix creates an index template for those index, so maybe you should provide related template permissions to es user
* Also an extra security permissions should be configured related to [this action](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-field-mapping.html)
* Rubrix use `ELASTICSEARCH` environment variable to set the es connection. You can provided credentials using the scheme: `http(s)://user:passwd@elastichost....`

Regarding access from a docker container, maybe you should make some [network adjustment](https://docs.docker.com/compose/networking/) before launch rubrix service.

**Comment by cceyda** [comment]
@frascuchon Thank you ~ 
I managed to get it working with the below role permissions
![image](https://user-images.githubusercontent.com/15624271/123934452-40e26000-d9ce-11eb-967d-a46a0b2afa1f.png)

Might be good to add this info to the docs 😃

**Comment by dvsrepo** [comment]
@cceyda  Thanks so much for your feedback! We'll definitely include this in the docs.

Also, we'd be pleased to answer and help with any question you might have, feel free to open an issue any time.
