### ISSUE TITLE
Error message when introducing predictions with unvalid format

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#191]
This example misled me:

```
{'Unnamed: 0': 0, 'id': 3334, 'text': '@sexyany99 Te daria $1000 x p*ta eso te mereces amor a mí me encantan las p*tas', 'label': 'discredit'}
ValidationError: 1 validation error for TextClassificationRecord
prediction
value is not a valid list (type=type_error.list)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-19-66b59178c1f9> in <module>
      4 
      5 for record in annotation_ds:
----> 6     records.append(rb.TextClassificationRecord(
      7         inputs=record["text"],
      8         annotation=record["label"],

~/Documents/RecognAI/rubrix/src/rubrix/client/models.py in __init__(self, *args, **kwargs)
    132     def __init__(self, *args, **kwargs):
    133         """Custom init to handle dynamic defaults"""
--> 134         super().__init__(*args, **kwargs)
    135         self.status = self.status or (
    136             "Default" if self.annotation is None else "Validated"

~/anaconda3/envs/rubrix/lib/python3.8/site-packages/pydantic/main.cpython-38-darwin.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for TextClassificationRecord
prediction
  value is not a valid list (type=type_error.list)
```

This error might be common, we can specify that a format error is happening and how to correctly format a prediction.

**Comment by frascuchon** [comment]
I've done some tests with pydantic and validation errors:

```python
class MyTestModel(BaseModel):

    a: List[str]
    b: int = Field(le=10)

a = MyTestModel(a="wrong_error", b=100) # This statement raise a validation error with 2 error info, but validation error has no referred value/data model in its context
```

The conclusion here is by using directly pydantic `ValidationError` instances we have no way of determine the value or model value that raised the error. So, it's hard to customize message errors including wrong value without a custom wrapper.

Maybe there is some info in [pydantic repository](https://github.com/samuelcolvin/pydantic)

**Comment by dvsrepo** [comment]
Understood!

Using @validator annotations like https://pydantic-docs.helpmanual.io/usage/validators/ at least for the most common fields like `prediction` and `annotation` in specific `model.py` files to add a more detailed message, is not an option right?

**Comment by frascuchon** [comment]
As far as I know, `@validaror` are used for custom or complex validations. If we use validators class methods, we would surely have to re-implement part of the validation logic. Maybe @ignacioct you could take a look on that

**Comment by dvsrepo** [comment]
Yes, definitely if we have to reimplement the validation logic that's definitely a no-go.

**Comment by dvsrepo** [comment]
After analyzing this, I've seen values will likely be included in the context of the validation errors for V2 of Pydantic so I guess we can close this until V2 arrives and we can upgrade (when FastAPI upgrades too)

**Comment by ignacioct** [comment]
> After analyzing this, I've seen values will likely be included in the context of the validation errors for V2 of Pydantic so I guess we can close this until V2 arrives and we can upgrade (when FastAPI upgrades too)

Yeah, I think we may.
