### ISSUE TITLE
Very minor OCD-inducing issue in Docs

### ISSUE THREAD

**Issue by Lord-V15** [argilla-io/argilla#201]
Hi, was wondering shouldn't the "Key phrase extraction" be a part of the list as all other tasks are mentioned below it ?
<img width="690" alt="Screenshot 2021-07-08 at 9 51 18 PM" src="https://user-images.githubusercontent.com/46837998/124957370-a2da3f80-e036-11eb-8c00-b49a0e2caa54.png">
I know. It's almost not even an issue. Just frustrates me every time I see it. Unless this was deliberate ?

**Comment by dvsrepo** [comment]
Very good catch @Lord-V15, thanks so much!
