### ISSUE TITLE
Searching for "!" leaves UI in a strange state

### ISSUE THREAD

**Issue by dcfidalgo** [argilla-io/argilla#211]
When searching for `inputs.text:!`, for example in `ree-grupos-interes-from-documents-with-spacy_v2` in our dev, a toast with an error appears and the UI gets into a strange state where filters are not working anymore.

**Comment by leiyre** [comment]
@frascuchon on query we get 500 (Internal Server Error), do you have any idea?

**Comment by frascuchon** [comment]
> @frascuchon on query we get 500 (Internal Server Error), do you have any idea?

maybe [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters) could be involved

**Comment by frascuchon** [comment]
We should include a better documentation for textual search, including reserved characters.

This requirement is noticed here #129
