### ISSUE TITLE
[UI] Refresh button overflows filter states

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla#225]
In annotation mode, the refresh button overflows the filter params, not allowing to remove them (for example the remove all button). See screenshot on Macbook Pro, Brave browser:

![image](https://user-images.githubusercontent.com/1107111/126074321-e860b0b7-cc93-4659-ae14-63287e169f1a.png)

**Comment by frascuchon** [comment]
Also for collapsed view of search controls 

<img width="1916" alt="Screenshot 2021-07-19 at 09 36 04" src="https://user-images.githubusercontent.com/2518789/126121064-cb01c8d9-5747-495e-ae17-524713408870.png">

**Comment by dvsrepo** [comment]
This should be solved with #159, check this issue when implemented
