### ISSUE TITLE
[Ui] New right sidebar

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/argilla#231]
Integrate new sidebar (in explore and annotation view)

UI layout in sketch

- [x] tooltip on hover each icons
- [x] icons style active/unactive
- [x] Token class view (Annotation progress, Stats: 1. Mentions 2. Error distrib)
- [x] Text class view (Annotation progress, Stats: 1. Keywords 2. Error distrib)

- [x] Integrate Progress and Stats widget behaviour
Small screen : deploy blocks as a new layer under the UI
Large Screen: Block are deployed by default on the right side, user can hide them by click on the icon bt

**Comment by dvsrepo** [comment]
Check and close related bug when ready #225 and #228
