### ISSUE TITLE
Remove "Validate" button for TextClassification in bulk actions

### ISSUE THREAD

**Issue by dcfidalgo** [argilla-io/argilla#243]
I think this button does nothing for TextClassification, right? @frascuchon @leiyre

**Comment by frascuchon** [comment]
You can select multiple records and validate predictions. I don't know what kind of use cases are covered by this feature, but it exists

**Comment by dcfidalgo** [comment]
ah, right. Maybe we could add tool tips that explain in a bit more detail what each button does, or rename the button to "Validate predictions".
