### ISSUE TITLE
[docs] Quick docs review

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla#26]
- [x] Simplify URL and folder structure by removing `documentation` from the path
- [x] Home page `index.rst` should be what's now **Introduction to Rubrix**. Ideally, this page will still be the first item of the Getting started block (I've seen this in other docs) but if it's not easy to do, no problem. 
- [x] Rename Introduction to Rubrix -> Rubrix docs
- [x] Add right-side table of contents (toc) to each page, with a header like "On this page".
- [x] Merge Concepts and Methods into one section called Concepts (I think is a heading issue).
- [x] Try to include the video on the home page with autoplay and using either html5 or a sphinx-contrib package.
- [x] Complete the home page (what's now Intro to Rubrix)
- [x] Complete missing things in Concepts (keep it as simple as possible).
- [x] Add Community section, with direct links to github and github discussion forum.

**Comment by ignacioct** [comment]
Wouldn't it be nice to add the direct links to github and the discussion forum on the Next Steps section of the first page (Intro to Rubrix)? Mainly because it would be an almost empty section, unless you want to include more things.

**Comment by dvsrepo** [comment]
Good idea, you can include them there. In any case we will be adding more
content in that part, with the goal of guiding the reader to the content of
the documentation.

**Comment by dcfidalgo** [comment]
@ignacioct I like. I would put a permanent link to GitHub somewhere in the header, i find it always super useful.
Ideally we want to have a PR for each of the items listed above, and check it once the PR is merged and put a reference there. Would you mind providing a PR for the items you already implemented?

**Comment by ignacioct** [comment]
I think this can be now closed, we've at least looked at everything here 😃
