### ISSUE TITLE
Issue While Lunching

### ISSUE THREAD

**Issue by somandra** [argilla-io/argilla#274]
rubrix_1         |   from cryptography.utils import int_from_bytes, int_to_bytes
rubrix_1         | [2021-08-14 01:26:08 +0000] [656] [INFO] Started server process [656]
rubrix_1         | [2021-08-14 01:26:08 +0000] [656] [INFO] Waiting for application startup.
rubrix_1         | [2021-08-14 01:26:08 +0000] [656] [ERROR] Traceback (most recent call last):
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
rubrix_1         |     (self._dns_host, self.port), self.timeout, **extra_kw
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
rubrix_1         |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
rubrix_1         |   File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
rubrix_1         |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
rubrix_1         | socket.gaierror: [Errno -2] Name or service not known
rubrix_1         | 
rubrix_1         | During handling of the above exception, another exception occurred:
rubrix_1         | 
rubrix_1         | Traceback (most recent call last):
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
rubrix_1         |     method, url, body, retries=Retry(False), headers=request_headers, **kw
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
rubrix_1         |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 507, in increment
rubrix_1         |     raise six.reraise(type(error), error, _stacktrace)
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
rubrix_1         |     raise value
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
rubrix_1         |     chunked=chunked,
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
rubrix_1         |     conn.request(method, url, **httplib_request_kw)
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
rubrix_1         |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
rubrix_1         |   File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
rubrix_1         |     self._send_request(method, url, body, headers, encode_chunked)
rubrix_1         |   File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
rubrix_1         |     self.endheaders(body, encode_chunked=encode_chunked)
rubrix_1         |   File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
rubrix_1         |     self._send_output(message_body, encode_chunked=encode_chunked)
rubrix_1         |   File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
rubrix_1         |     self.send(msg)
rubrix_1         |   File "/usr/local/lib/python3.7/http/client.py", line 972, in send
rubrix_1         |     self.connect()
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
rubrix_1         |     conn = self._new_conn()
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
rubrix_1         |     self, "Failed to establish a new connection: %s" % e
rubrix_1         | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3dfbd1b590>: Failed to establish a new connection: [Errno -2] Name or service not known
rubrix_1         | 
rubrix_1         | During handling of the above exception, another exception occurred:
rubrix_1         | 
rubrix_1         | Traceback (most recent call last):
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 526, in lifespan
rubrix_1         |     async for item in self.lifespan_context(app):
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 467, in default_lifespan
rubrix_1         |     await self.startup()
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 502, in startup
rubrix_1         |     await handler()
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/rubrix/server/server.py", line 73, in configure_elasticsearch
rubrix_1         |     datasets: DatasetsDAO = create_datasets_dao(es=es_wrapper)
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/rubrix/server/datasets/dao.py", line 271, in create_datasets_dao
rubrix_1         |     _instance = DatasetsDAO(es)
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/rubrix/server/datasets/dao.py", line 66, in __init__
rubrix_1         |     self.init()
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/rubrix/server/datasets/dao.py", line 73, in init
rubrix_1         |     force_recreate=True,
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/rubrix/server/commons/es_wrapper.py", line 152, in create_index_template
rubrix_1         |     self.__client__.indices.put_template(name=name, body=template)
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
rubrix_1         |     return func(*args, params=params, headers=headers, **kwargs)
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 647, in put_template
rubrix_1         |     body=body,
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 413, in perform_request
rubrix_1         |     raise e
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 388, in perform_request
rubrix_1         |     timeout=timeout,
rubrix_1         |   File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 264, in perform_request
rubrix_1         |     raise ConnectionError("N/A", str(e), e)
rubrix_1         | elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3dfbd1b590>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3dfbd1b590>: Failed to establish a new connection: [Errno -2] Name or service not known)

Getting this error while launching rubrix server. Please help in configuring docker-compose.yml File to launch it on localhost. Tries changing environment.ELASTICSEARCH variable but didn't work getting the same error.

**Comment by frascuchon** [comment]
Hello @somandra 

Thanks for you quesion.

Did you follow the setup & installation instructions?  Are you running elasticsearch from same docker-compose configuration file?

You can check to launch first elasticsearch and be sure is running properly:

```bash
$>docker-compose up -d elasticsearch
$>docker-compose logs -f elasticsearch
```
then, you can launch the rubrix service:

```bash
docker-compose up rubrix
```

Or, if you don't worry about stored data, you can reset everything:

```bash
docker-compose down && docker-compose up 
```

**Comment by dvsrepo** [comment]
Hi @somandra did you manage to solve this issue?

**Comment by dvsrepo** [comment]
@somandra I'm closing this issue but feel free to reopen if you need more help or find more issues.

**Comment by somandra** [comment]
elasticsearch    | ERROR: [1] bootstrap checks failed
elasticsearch    | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch    | ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/es-rubrix-local.log
elasticsearch    | {"type": "server", "timestamp": "2021-09-11T02:27:41,750Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "es-rubrix-local", "node.name": "elasticsearch", "message": "stopping ..." }
elasticsearch    | {"type": "server", "timestamp": "2021-09-11T02:27:41,794Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "es-rubrix-local", "node.name": "elasticsearch", "message": "stopped" }
elasticsearch    | {"type": "server", "timestamp": "2021-09-11T02:27:41,795Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "es-rubrix-local", "node.name": "elasticsearch", "message": "closing ..." }
elasticsearch    | {"type": "server", "timestamp": "2021-09-11T02:27:41,842Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "es-rubrix-local", "node.name": "elasticsearch", "message": "closed" }
elasticsearch    | {"type": "server", "timestamp": "2021-09-11T02:27:41,850Z", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "es-rubrix-local", "node.name": "elasticsearch", "message": "Native controller process has stopped - no new native processes can be started" }
elasticsearch exited with code 78

**Comment by somandra** [comment]
Hi @dvsrepo I tried initiating elastic search but facing this error. Elastic search is not starting properly

**Comment by frascuchon** [comment]
Hi @somandra 

We've updated docker-compose.yml configuration. You can either re-download .yml file and execute as normal or manually setup elasticsearch in dev mode. For that, the only change is replace line:

```yaml
- cluster.initial_master_nodes=elasticsearch
```

by:

```yaml
- discovery.type=single-node
```

Thanks for your  feedback!!!

**Comment by somandra** [comment]
Thanks @frascuchon for your help. It's working now

**Comment by frascuchon** [comment]
Great! happy to hear that @somandra. Comments welcome if you have troubles in future

I will close the issue.
