### ISSUE TITLE
Is there a functionality to add system admin, project admin and further annotators for different projects?

### ISSUE THREAD

**Issue by gwork91** [argilla-io/argilla#279]
Something similar to Django application, where all these functionalities are present

**Comment by dvsrepo** [comment]
Hi @palashgoyal1 ,

Thanks for your question! 

Basic user management (add annotators) is now available on master, and will be included in the next release. For the moment, more advanced user management (Access Control Lists, User groups) is not planned in the short term, but we're always looking for ideas and even contributions.

You can find the docs here: https://rubrix.rtfd.io/en/master/getting_started/advanced_setup_guides.html#user-management

Please let us know if you test it and have further questions or suggestions.
