### ISSUE TITLE
New UI Features

### ISSUE THREAD

**Issue by dcfidalgo** [argilla-io/argilla#29]
Here are a few features for the UI that would be awesome to have :)

- Apply annotations to all records of a given filter combination. Right now i can only select all records shown on screen and annotate them at once, but i cannot select all records of the given filter combination.
- It would be nice to be able to load more than 5 records at once. Sometimes i need to go through a given filter combination rapidly to reach a certain point, and it is a bit cumbersome to press x times "Next 5 records".
- In general it would be a nice feature to be able to "mark" records (maybe with a color or something like that). In my use case i had to check all negative annotated samples and reannotate them if necessary. Right now there is no way to "save" this progress, that is i could not mark the record as "i already checked you". Another use case was that we wanted to "mark" some phone calls we found via the UI, that had a really bad transcription. We used the "discard" feature for this, but this is not what it was meant for.
- Allow to dynamically add/change/remove labels. Right now we have to do this outside of the UI, by loading/logging the data set again. Use case would be: while annotating, i see that the labels are not really suitable, and i want to add/change/remove some.

**Comment by dvsrepo** [comment]
Quick feedback:

💯 agree with **1** and **2**! I

For 1: This is something that I've missed a lot when using it for the knowldge graph use case, where you can have very precise filters and thus "safely" annotate a lot of records. This could look be similar to what gmail does to apply a tag to all results on a search query, maybe with a warning for the user.
For 2: I would even add the possibility to select the range you feel comfortable with from a dropdown (Show 5, 10, 20, 50 records)

The other two as well but I need to think a bit more about them!

**Comment by dcfidalgo** [comment]
Another request:
- Show annotation/prediction agent in the metadata. Sometimes i want to quickly check, who made the annotation and it would be nice if this information was included in the window when you press "View metadata"
- Make adding a new label for `TextClassification` records more visible, it's hard to find in the `Annotate as` dropdown [**Done**]

**Comment by dvsrepo** [comment]
can we maybe move this to the Discussion forum into one or several messages/threads? @dcfidalgo

**Comment by dcfidalgo** [comment]
Done #102
