### ISSUE TITLE
New records pagination system 

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla#290]
We want to implement a "classical" pagination system, with the following features:

- Analyze best practices and visualization options.
- No "infinite" scroll.
- Show X records per page, the user can select the number of records per page (1, 5, 10, 25, 50).
- The URL params will store necessary info to recreate the state in the URL, so users can share URLs to a specific region of the dataset.

**Comment by leiyre** [comment]
@dvsrepo @frascuchon, as mentioned above, let's see which type and functionality is best suited to Rubrix. 

Here are some articles about the different ways of pagination and some advice:
https://uxdesign.cc/ui-cheat-sheet-pagination-infinite-scroll-and-the-load-more-button-e5c452e279a8#--responses
https://medium.com/uxness/best-practices-for-designing-pagination-in-web-1c33140f31b

a) Do we want to paginate by page number or by record range?
![Captura de pantalla 2021-08-30 a las 12 49 40](https://user-images.githubusercontent.com/20307370/131328375-d76f881a-f175-429f-8bdc-9cff0f98ef4f.png)
### 

b) What functionality do we want?
-We want to specify the number of items per page
-Advance to the first/last page
-View the total number of pages
-Show n number of pages and be able to navigate directly to some pages or only be able to navigate to the previous or next page.
-To be able to navigate to a specific page number

These are some options:

1:
![Captura de pantalla 2021-08-30 a las 12 01 32](https://user-images.githubusercontent.com/20307370/131329585-58097a5b-b750-41f2-ada2-ddbd7b313901.png)
2:
![Captura de pantalla 2021-08-30 a las 12 30 00](https://user-images.githubusercontent.com/20307370/131328972-cc733c34-c086-4e63-8201-9e52e05d424f.png)
3:
![Captura de pantalla 2021-08-30 a las 12 03 24](https://user-images.githubusercontent.com/20307370/131328976-8c8659b9-0e73-49cb-891f-107639faf206.png)
4:
![Captura de pantalla 2021-08-30 a las 11 51 54](https://user-images.githubusercontent.com/20307370/131328979-943bf51f-59df-4c14-8e9f-807880ffff88.png)
5:
![Captura de pantalla 2021-08-30 a las 13 00 09](https://user-images.githubusercontent.com/20307370/131329487-4333522e-af09-423d-a258-5c379c98fdc3.png)

**Comment by frascuchon** [comment]
Nice analysis

In my opinion, I think showing pagination info at page level could be fit better if we want directly move to a specified page (for annotation this could be nice for selective rollback). The "Go to page" action could be nice just for large search results. So it could be conditionally shown.

**Comment by dcfidalgo** [comment]
Nice!! I would vote for pagination by record range, and maybe some simple interface like option 1 or 2. But 4 looks also appealing to me :) ... no strong opinion here.

**Comment by dvsrepo** [comment]
Personally, I like example 4, if I understand correctly it covers:

1. Access first pages quickly
2. Access the last page
3. Access previous and next page
3. Shows record range for the current page
4. Allows selecting how many records to show per page (I guess the number and distribution of pages gets updated when changing this)
