### ISSUE TITLE
Add a right-side toc with "On this page" information when support to that feature is added

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#30]
It will be eventually be supported as a theme option ([issue os sphinx referencing it](https://github.com/readthedocs/sphinx_rtd_theme/pull/919)). If not, it would require CSSing it out, or picking another base theme. Pytorch-lighting is able to do this [in their docs](https://pytorch-lightning.readthedocs.io/en/latest/#)

This concept is called `local_toc`.

**Comment by dvsrepo** [comment]
we can close this
