### ISSUE TITLE
Review sort component

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla#302]
Only some minor improvements:

- The component should work as the filters: indicating the number of active sorting fields: for example (1) if one field is selected for sorting.
- The dropdown list elements should have the hand pointer on hover, not the arrow pointer (maybe we could review all other dropdowns, I remember having the same issue with another dropdown.
-  What happens when we have a long list of fields? If possible I'd enable search as well for this dropdown.
- What happens when the users define a metadata field with the same name as one of the reserved fields? e.g., `metadata.Status` (I think this is possible @frascuchon ?) In this case we'll have two Status on the list.
- Add more top and bottom padding to the dropdown box. 

As a broader comment, our URL params look a bit ugly with the encoding, ideally we should have clear text for the param values,  I'm not sure if this is something we could fix with nuxtjs config or other solution.

**Comment by frascuchon** [comment]
We could encode/decode each url param (at least query params and sort order). Some like this:

[https://rubrixhost/my-dataset?query=eyJxdWVyeSI6ICJ0ZXh0IiwgIm1ldGFkYXRhIjogeyAiYSI6ICJibGRraiJ9fX0=&annotationMode=true&sort=eyJxdWVyeSI6ICJ0ZXh0IiwgIm1ldGFkYXRhIjogeyAiYSI6ICJibGRraiJ9fX0=]()

**Comment by dvsrepo** [comment]
Yes, that would help. 

Because I guess that having clear URL query params will be problematic no? (https://forum.vuejs.org/t/router-push-encodes-special-characters/35015) and they'd still be difficult to read..

**Comment by frascuchon** [comment]
About your comment:

> What happens when the users define a metadata field with the same name as one of the reserved fields? e.g., metadata.Status (I think this is possible @frascuchon ?) In this case we'll have two Status on the list.

Yes, this case could happen. Maybe we can include `metadata.` prefix for metadata fields ? Or another group for metadata fields, like filters?

**Comment by dvsrepo** [comment]
I'd vote for the prefix metada.

**Comment by Amelie-V** [comment]
- The arrow bt doesnt work today
- Align on the left side "cancel/apply" bt
- When selector is open cut the label name (= selector is closed)
- Group Sort feature with other filters + add icon

**Comment by Amelie-V** [comment]
![Captura de pantalla 2021-09-13 a las 14 46 38](https://user-images.githubusercontent.com/84135211/133086043-aa33657d-caa4-477d-a40f-7f8840c5532e.png)
![Captura de pantalla 2021-09-13 a las 14 46 33](https://user-images.githubusercontent.com/84135211/133086046-2f79b36f-891c-4c0d-bcf8-98a534b1feb8.png)

**Comment by Amelie-V** [comment]
- change "add field +" to "+ Add another field "
