### ISSUE TITLE
Readme review

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla#309]
Feel free to leave comments, suggestions and feedback in the comments.

**Comment by ignacioct** [comment]
Hey guys! I really like this new iteration of the README, good job! Now that it is a little bit longer and has many sections, I would find useful a little tree of content at the beginning, so people can skip to any desired part.

You commented that you think it is difficult to see what Rubrix does upfront. Maybe I'm a little bit biased, but the video is very helpful in explaining the UI part, and the example explains the Python part very well. I did not struggle in that part.

Good job! 👏

**Comment by christinabo** [comment]
Hey all!
It's the first time I came across this project but I found it interesting and I thought it's a good idea to have a proper look.
First of all, congratulations, great job in putting such a tool together!

Some comments about the readme:
1. The video is very informative and the key features are very well put, they give you the gist of why this is unique. The only thing for me is the Get Started section, I'd probably move it a bit up, before the Example section, for example, but not a big deal 👍 
2. I started running the [example](https://github.com/recognai/rubrix/#1-predict-and-log) but when it comes to the [second step](https://github.com/recognai/rubrix/#2-explore-filter-and-label), I don't seem able to get the annotation option in the UI, as shown in the `Zeroshot.Example.mp4` video; I'm only able to explore the data samples. Is this behaviour expected? Sorry if I'm just missing something 😊 

Please take my comments with a pinch of salt as I didn't spend that much time on it! Congrats again 👏

**Comment by dvsrepo** [comment]
Thanks so much, @christinabo this is the type of feedback we are looking for.

For 1. I think you are completely right, we'll try to put a getting started section before the Example, maybe a minimal version with a link to the detailed section.

For 2. I guess (and hope) it's due to the sidebar option not being very clear, we're working on a new version to make how to change between modes (Explore, Annotation) more clear. Could you please confirm if you see the following:

<img width="574" alt="Screenshot 2021-09-13 at 12 16 15" src="https://user-images.githubusercontent.com/1107111/133067089-ec4d63a1-d3b5-4abf-b006-be0afbadada2.png">

With that switch you should be able to enter the annotation mode and start labeling records. Otherwise, it could be a version problem. You could check that this way:

```python
import rubrix as rb
print(rb.__version__)
```

**Comment by christinabo** [comment]
> Thanks so much, @christinabo this is the type of feedback we are looking for.
> 
> For 1. I think you are completely right, we'll try to put a getting started section before the Example, maybe a minimal version with a link to the detailed section.
> 
> For 2. I guess (and hope) it's due to the sidebar option not being very clear, we're working on a new version to make how to change between modes (Explore, Annotation) more clear. Could you please confirm if you see the following:
> 
> <img alt="Screenshot 2021-09-13 at 12 16 15" width="574" src="https://user-images.githubusercontent.com/1107111/133067089-ec4d63a1-d3b5-4abf-b006-be0afbadada2.png">
> 
> With that switch you should be able to enter the annotation mode and start labeling records. Otherwise, it could be a version problem. You could check that this way:
> 
> ```python
> import rubrix as rb
> print(rb.__version__)
> ```

Oh, of course, I can see this button now and clicking on it _does_ enable the annotation. 
I was interacting with the rest of the buttons in that sidebar but I think I might have missed that one because it seemed as if it was inactive with the grey colour.
It makes sense now! Thank you 👍

**Comment by dvsrepo** [comment]
Great! We're completely redesigning the sidebar to improve that behavior, thanks so much for the feedback! Please feel free to share anything with us.

**Comment by dvsrepo** [comment]
> Hey guys! I really like this new iteration of the README, good job! Now that it is a little bit longer and has many sections, I would find useful a little tree of content at the beginning, so people can skip to any desired part.
> 
> You commented that you think it is difficult to see what Rubrix does upfront. Maybe I'm a little bit biased, but the video is very helpful in explaining the UI part, and the example explains the Python part very well. I did not struggle in that part.
> 
> Good job! 👏

Thanks so much @ignacioct ! We'll take the ToC recommendation into account!

**Comment by dvsrepo** [comment]
> Hey all! It's the first time I came across this project but I found it interesting and I thought it's a good idea to have a proper look. First of all, congratulations, great job in putting such a tool together!
> 
> Some comments about the readme:
> 
> 1. The video is very informative and the key features are very well put, they give you the gist of why this is unique. The only thing for me is the Get Started section, I'd probably move it a bit up, before the Example section, for example, but not a big deal 👍
> 2. I started running the [example](https://github.com/recognai/rubrix/#1-predict-and-log) but when it comes to the [second step](https://github.com/recognai/rubrix/#2-explore-filter-and-label), I don't seem able to get the annotation option in the UI, as shown in the `Zeroshot.Example.mp4` video; I'm only able to explore the data samples. Is this behaviour expected? Sorry if I'm just missing something 😊
> 
> Please take my comments with a pinch of salt as I didn't spend that much time on it! Congrats again 👏

Thanks so much for your feedback again @christinabo we have just applied your suggestion to the README. Also, we're actively looking for feedback, hearing about use cases, and even contributions. I would love to know about your impressions and also if we can support you for getting started. Please do not hesitate to reach us.
