### ISSUE TITLE
[New Feature]: Team workspaces

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/argilla#310]
UX-UI

- Show active session
- Show team's workspaces
- Allow to switch between team's workspace
- Include logout  

Client: (resolved in #661)

- [x] allow configure active workspace in init / environment var 
- [x] allow to change active workspace
- [x] query active workspace

**Comment by frascuchon** [comment]
@dcfidalgo @dvsrepo  Remember: we must define how teams take in place for python client.
