### ISSUE TITLE
Streamlit app section on docs

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#32]
Adding the streamlit app section on documentation. Streamlit app is already developed.

How shall I proceed @dvsrepo ? Making a quick .rst file just showing how to run the app (as all the explanations are in the code) or explaining the app/what the app shows in the .rst ?

**Comment by dvsrepo** [comment]
I would recommend to:

1. Briefly explain the goal: "The goal is to show you how you can integrate
Rubrix into third-party ML applications to collect predictions and
user-feedback. For this we will use streamlit with a model, bla-bla"
2. Briefly explain what the app does, the user/data flow and maybe show
relevant code snippets related to rubrix calls explaining what they do.
3. Tell the user how to run the app. I think it might be a good idea to
create a repo at recognai/streamlit-rubrix-example and have there the app
with the requirements.txt and the command to run it, cross-referencing back
to rubrix docs. Something simple like: here's the repo to explore the code
and run the app yourself.

What do you think?


*Daniel Vila Suero*

CEO & Co-founder

Tel: +34 679120675

www.recogn.ai

<http://www.recogn.ai/>
[image: Recognai Twitter] <https://twitter.com/recogn_ai> [image: Recognai
Linkedin] <https://www.linkedin.com/company/recognai/>

**Comment by ignacioct** [comment]
I didn't know you could nest repositories, but it might be a cool ideal. You want me to create that repo with recognai's account, or with mine?

I totally agree with all the points, I'll try to follow a minimal approach and to make a rather small, but meaningfull .rst

**Comment by dvsrepo** [comment]
We can create it with Recognai account. The idea is to include the app and
requirements.txt there and just add a link from the docs, probably I was a
bit fuzzy explaining the cross referencing part :-D

**Comment by ignacioct** [comment]
Okay, I think I get it. Even though we have the app in the folder structure, we have referenced a github link with an isolated repository for people to mess around.

**Comment by dvsrepo** [comment]
Yes! And then eventually remove the app from this repo (we can decide that
afterwards)
