### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#39]
Hi! I think we've moved enought in the documentation process to update our beautiful README. In my opinion, two main tasks have to be adressed:

- Decide if we change the actual content of the readme (many of this things are now on separate documentation section).
- Complete what's left (some code blocks are placeholders, for example)

So we can discuss here how to approach this. My proposal:

1. First paragraph and quick links stays, but quick links could maybe be at the bottom of the readme.
2. Use cases look cool there, but I think design principles is info overloading. We can either move it to an existing doc page (Introduction feels right to me).
3. Main concepts have their own place now to be. We could maintain a copy here too, I'm down to anything here.
4. Get started coul be a little bit reduced, and placed before main concepts. We would reference the full instructions doc page. I see this **get started** as a **I want to test Rubrix in less than a minute to test something out**, and the docs **get started** as a **that was cool! something cool enough for me I even made it to the documentation**.
5. Supported and planned tasks feels right to me here, we give a glance at we have done and what are we working on from the readme. 

Tell me what do you think 🤠

**Comment by dcfidalgo** [comment]
My 22 cents:

> 1. First paragraph and quick links stays, but quick links could maybe be at the bottom of the readme.

Not sure if Quick links is necessary here, i would put a link to the docs in the first paragraph at the end and remove this section.
> 2. Use cases look cool there, but I think design principles is info overloading. We can either move it to an existing doc page (Introduction feels right to me).

I agree, the first paragraph already outlines some use cases. I think in the docs we can elaborate more on use cases.
> 3. Main concepts have their own place now to be. We could maintain a copy here too, I'm down to anything here.

+1 for removing this section
 > 4. Get started coul be a little bit reduced, and placed before main concepts. We would reference the full instructions doc page. I see this get started as a I want to test Rubrix in less than a minute to test something out, and the docs get started as a that was cool! something cool enough for me I even made it to the documentation.

I think the `Get started` section is fine, not sure if it can be reduced further without missing its purpose. However, i would switch number 1 and 2, that is first install the client, then run docker compose or install the client with the server deps.
 > 5. Supported and planned tasks feels right to me here, we give a glance at we have done and what are we working on from the readme.

I would substitute this section with something like `Next steps`, where we put more specific links to our documentation, like to the tutorials, main concepts, supported tasks ...  If we leave development stuff here, i'm afraid they get outdated rapidly. Maybe we can open a thread in Discussions about planned/requested tasks, and leave a link in the readme.

**Comment by dvsrepo** [comment]
I agree with your proposal and @dcfidalgo suggestions. Please go ahead. My only suggestions would be:

-  To add the rubrix_intro.svg diagram close to the top part of the readme as I think it helps to get a kick idea.
- Get started/quick start where readers see some basic code I think are essential for promoting this type of library/tool.

**Comment by dvsrepo** [comment]
Just one more thing not to forget, if we remove `Supported tasks` please move them into the Get started docs module as a new section and we will improve them over time.

**Comment by ignacioct** [comment]
> Just one more thing not to forget, if we remove `Supported tasks` please move them into the Get started docs module as a new section and we will improve them over time.

Yeah, I think **Supported task** can be moved to **Get Started**, even as a final destination.

**Comment by ignacioct** [comment]
> I think the `Get started` section is fine, not sure if it can be reduced further without missing its purpose. However, i would switch number 1 and 2, that is first install the client, then run docker compose or install the client with the server deps.

@dcfidalgo , I think dani or paco put it in this order because install the client can be skipable if you follow what is now 1b.

**Comment by dcfidalgo** [comment]
> @dcfidalgo , I think dani or paco put it in this order because install the client can be skipable if you follow what is now 1b.

You are right, let's just leave it as is.
