### ISSUE TITLE
UI fine tuning styles

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/argilla#42]
- [x] H1 Futura 36pt
- [x] H2 Futura 28pt
- [x] Text O.S 16px
- [x] Menu O.S 14px
- [x] Chapter title in menu no clickable (ej; Getting start) : Futura, soft blue : 4C4EA3, 22pt
- [x] Code snippet: same grey border and text color (pink): F2067A

**Comment by Amelie-V** [comment]
- [x] Change highlight color in search results #c5c6e0
- [x] Change API ref color : #c5c6e0 and #4C4EA3
- [x] Search box : when actived, change light blue to light grey

**Comment by Amelie-V** [comment]
![Captura de pantalla 2021-05-19 a las 14 18 37](https://user-images.githubusercontent.com/84135211/118811528-68adb680-b8ad-11eb-9573-577541f94c2d.png)
![Captura de pantalla 2021-05-19 a las 14 12 41](https://user-images.githubusercontent.com/84135211/118811552-6cd9d400-b8ad-11eb-9ccd-554f510f7b7c.png)

**Comment by Amelie-V** [comment]
![Uploading Captura de pantalla 2021-05-19 a las 14.21.29.png…]()

**Comment by dvsrepo** [comment]
Can we close this @Amelie-V  and @leiyre ?
