### ISSUE TITLE
URL not found for images

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla#43]
When clicking on the images in the docs you get to a not found url. There are several solutions:

1. remove the ability to click on the image.
2. maybe there's an sphinx-contrib for enlarging/full-screen the image.
3. Fix the path

I don't know which one is easier to do, maybe 2 is the most difficult, I let you decide. In general I would avoid sending the users to other urls and leaving the docs, even if it's our image

**Comment by dcfidalgo** [comment]
Number 1 is easy, we just have to remove the `:target:` option in the `.. image` directives.
I did a quick search for option 2, but did not find anything. Maybe for now we can go option 1, and try to go for option 2 in the near future.

**Comment by dvsrepo** [comment]
Yes! let's go for number 1 definitely
