### ISSUE TITLE
[BUG-UI/UX] Why the newline sign not be seen on UI？

### ISSUE THREAD

**Issue by duguwanglong** [argilla-io/argilla#4458]
I take some newline signs in the strings, but the newline can not be seen on the UI.
![image](https://github.com/argilla-io/argilla/assets/48522006/7f426419-8c69-4b80-97d8-6cf4f9b65c7b)
![image](https://github.com/argilla-io/argilla/assets/48522006/a3f7505c-f1b3-4256-a5b2-6cf25768d6d7)

**Comment by davidberenstein1957** [comment]
@duguwanglong, we only use markdown rendering for the new `FeedbackDataset`.

You can find an overview of the differences between the dataset here: https://docs.argilla.io/en/latest/practical_guides/choose_dataset.html
Also, we've got a nice overview of [making most of markdown and HTML rendering](https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/making-most-of-markdown.html).
