### ISSUE TITLE
[UX] Search box improvement ¨Next Release¨

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/argilla#459]
We are looking for a solution to make more efficient the use of the search box especially when user is doing several researches in a row.

Solutions to discuss:

- When user clear the last character into the search box, refresh automatically the search.
- When user clear the last character, maintain the cross "X" (rather than showing again "the Search icon" + "placeholder text field") and allow new search when click on the cross "X" is done.
-  .. suggestions

**Comment by dcfidalgo** [comment]
I would vote for the second solution, basically giving the "X" the functionality of removing the "search filter".
