### ISSUE TITLE
[REFACTOR] Improve handling of question models and dicts

### ISSUE THREAD

**Issue by burtenshaw** [argilla-io/argilla#4931]
We can improve code quality and reduce redunancy by using a pydnatic type annotator instead of identical methods on each cleas:

@frascuchon gives an example here: https://github.com/argilla-io/argilla-python/pull/195#discussion_r1604995059

**Comment by frascuchon** [comment]
@burtenshaw This could be part of a wider issue to align questions to Resource class and finally allow update settings for questions
