### ISSUE TITLE
QUESTION: Global actions validation for text classification with multi label

### ISSUE THREAD

**Issue by frascuchon** [argilla-io/argilla#499]
Making annotations for multi class text classification dataset I've realized that using global action for group validation ("Annotate as..." action) doesn't work like I've expected.

Selecting labels from global actions should totally overwrite labels for selected records. Instead of that, the selected labels are merged with already defined in records.

What would be the appropriate behavior  in this case @dvsrepo @dcfidalgo @Amelie-V @leiyre ?

**Comment by dcfidalgo** [comment]
For me definitely overwriting the existing annotations.

**Comment by dvsrepo** [comment]
Same for me

**Comment by frascuchon** [comment]
Ok I will open a UI issue
