### ISSUE TITLE
Text2Text: View annotation/prediction, bug?

### ISSUE THREAD

**Issue by dcfidalgo** [argilla-io/argilla#509]
In Exploration mode: When you press "View annotation" in a record, then go to another record and press "View annotation", the former record switches to showing the prediction again. In Annotation mode, it is the other way around. @leiyre Not sure if this behavior is desired or if it is a bug.

**Comment by leiyre** [comment]
@dcfidalgo, I think this is the normal behaviour. By default the exploration mode view shows the prediction and the annotation mode view shows the annotation. When we change the view of a record and click out of it, it reverts to the default view of the record.

**Comment by dcfidalgo** [comment]
ah ok, so it's not so much the click on the other "View annotation", but rather the click outside. Not sure if it is more intuitive to leave the "view state" as is in this case, rather than reverting to the default view ... anyways, it's a minor thing, will close this issue.
