### ISSUE TITLE
[bug] Filter by annotated_as doesn't seem to work for text2text

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla#512]
Not sure if it's related to the query. Also, I am still unsure we'd like to filter by annotated_as in text2text as texts will be potentially long and likely unique. We could consider not showing this filter at all, what do you think? @dcfidalgo @frascuchon @Amelie-V

**Comment by dcfidalgo** [comment]
+1 for not showing... I think the only "annotated_as" filter that makes sense for text2text is kind of a search box that only searches the annotations.

**Comment by frascuchon** [comment]
`Text2Text` API doesn't support `annotated_as` or `predicted_as` filters: 

Here the search query schema for text2text:

<img width="1000" alt="Screenshot 2021-10-27 at 14 48 16" src="https://user-images.githubusercontent.com/2518789/139068603-81287564-e498-4371-9659-5f0bba12492c.png">
