### ISSUE TITLE
svg images with white font

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#54]
While implementing the new readme, and adding one of the amazing svg images we have to explain Rubrix, and as a dark mode Github user, I came across this: 

![Captura de pantalla 2021-05-19 a las 12 08 46](https://user-images.githubusercontent.com/56955040/118795543-f92ecb80-b89a-11eb-9843-1ec5b921d8b5.png)

Is it possible to make it a png-like background, or we stick to the light mode approach?

**Comment by dcfidalgo** [comment]
Seems they are working on this feature: https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/26

I would say we stick to the white version, even if it looks a bit off in dark mode. @Amelie-V Or is there an easy fix for this image to look great regardless of light/dark mode?

**Comment by dvsrepo** [comment]
I would also say we stick with the white version, as:

-  we do not have control over dark mode in github,
- I am not sure how to have a single-version which works well in github
dark-mode, github light mode and our white docs
- and for maintenance reasons (not having to update two versions of
the diagram)

Unless @Amelie-V <https://github.com/Amelie-V>  has a great suggestion
which is easy to implement. I am using draw.io and I could share the main
project with the team if interested, I have many more of this sort of
explanation diagrams for the Use cases which I will be including as soon as
possible.


*Daniel Vila Suero*
CEO & Co-founder

Tel: +34 679120675

www.recogn.ai

<http://www.recogn.ai/>
[image: Recognai Twitter] <https://twitter.com/recogn_ai> [image: Recognai
Linkedin] <https://www.linkedin.com/company/recognai/>

**Comment by Amelie-V** [comment]
mmm maybe we can check if draw.io allows transparent .png?

**Comment by dvsrepo** [comment]
Yes, I could export it as transparent .png to do the test but I guess we'll
have a contrast issue with dark blue and black background. Maybe is a
matter of changing the dark blue main colour to the pink one?

I'll export one and share it with you to discuss it


*Daniel Vila Suero*
CEO & Co-founder

Tel: +34 679120675

www.recogn.ai

<http://www.recogn.ai/>
[image: Recognai Twitter] <https://twitter.com/recogn_ai> [image: Recognai
Linkedin] <https://www.linkedin.com/company/recognai/>

**Comment by ignacioct** [comment]
Well, I think this can be closed, as we already updated the images to transparent font. Closing it, reopen if we need to discuss something 😄
