### ISSUE TITLE
Rule to show show green/red/no icon

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/argilla#67]
- [x] Check the logic implemented correspond to this behaviour

Gold same as Annotation: Green 
Gold different as Annotation: Red 
No Annotation or no Gold : No icon

**Comment by leiyre** [comment]
@Amelie-V I can'f find any example of a record without annotation or predictions, I can find some examples with predictions of 0, In this case, there will no icon?

**Comment by Amelie-V** [comment]
https://XXXXXXXXX/kg_node_classification_unseen_nodes?query=%7B%22predicted_as%22%3A%5B%22Meaty%22%5D,%22metadata%22%3A%7B%7D%7D&sort=%5B%5D&task=TextClassification&allowAnnotation=false

**Comment by dvsrepo** [comment]
can we close this @Amelie-V  and @leiyre ?
