### ISSUE TITLE
Add label Feature

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/argilla#68]
- [x] Integrate new user flow
Cuando te pongas hablamos para validarlo

- [x] Display records group like blogs
- [x] Align the creation of labels and entities

**Comment by Amelie-V** [comment]
![Uploading User flow Add label.png…]()

**Comment by Amelie-V** [comment]
![Uploading User flow Add label.png…]()

**Comment by Amelie-V** [comment]
![User flow Add label 2](https://user-images.githubusercontent.com/84135211/118958654-e7642b80-b961-11eb-954f-1181bfe025c6.png)

**Comment by Amelie-V** [comment]
<img width="345" alt="Captura de pantalla 2021-05-26 a las 14 23 14" src="https://user-images.githubusercontent.com/84135211/119658898-f1889d00-be2d-11eb-818e-df674f894281.png">
<img width="381" alt="Captura de pantalla 2021-05-26 a las 14 23 03" src="https://user-images.githubusercontent.com/84135211/119658918-f51c2400-be2d-11eb-808d-984068312f7e.png">

**Comment by Amelie-V** [comment]
Revisar los estilos, la info y tamaños.
En los 2 screenshot, abajo esta el diseño original

**Comment by Amelie-V** [comment]
El nuevo label creado debe ponerse siempre a la cola de los existentes y no despues del record anotado. (view SS)

**Comment by Amelie-V** [comment]
![Uploading Captura de pantalla 2021-05-26 a las 14.15.48.png…]()

**Comment by dvsrepo** [comment]
can we close this @Amelie-V  and @leiyre ?
