### ISSUE TITLE
Moving api reference to api folder

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#71]
I've noticed that we have an empty api folder, and the api reference is inside _reference_ folder. We can merge both into the _api_ folder, if you see it right @dcfidalgo

**Comment by dcfidalgo** [comment]
hm, i don't see the api folder: https://github.com/recognai/rubrix/tree/master/docs
But yes, let's put all future content of the *Reference* section simply in the *reference* folder.

**Comment by ignacioct** [comment]
It seems that empty folders are not uploaded into git. I will just erase it in my local environment, and once y make a merge, it will be gone forever. I'm closing this, thank you!
